<a href="https://colab.research.google.com/github/SangMin316/Numerical-Methods-in-Engineering-with-Python/blob/main/linear%20equation%20solve%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Why do we use Numpy?

In [7]:
import numpy as np
# numpy array는 연산을 캐쉬 메모리안에서 해서 접근이 빠르다
# list 로 할떄도 행우선 연산인지, 열우선 연산인지에 따라 속도가 다름
# 이유는 블록단위로 캐쉬메모리에 정보를 올리기 때문에
A_np = np.ones((3000,3000)) 
import time
start_time = time.time()

for i in range(3000):
    for j in range(3000):
        A_np[i,j] = A_np[i,j] + 1

end_time = time.time()
k = end_time - start_time
print(k)



5.581942319869995


In [8]:
start_time = time.time()
A_np = A_np + A_np
end_time = time.time()
k = end_time - start_time
print(k)


0.017991304397583008


Numpy is faster than forloop 

#LU decomposition




####A = [[4,3] ,[6,3]]
####L = [[1,0],[L21,1]]
####U = [[U11, U12], [0 ,U22]]
####LU = [[U11, U12] ,[U11*L12, L12*U12 + U22]]
U11 = 4, U12 = 6, L21 = 6/4, U22 = -3/2 


In [9]:
L = np.array([[1,0],[6/4,1]])
U = np.array([[4,6],[0,-3/2]])

print(L*U) 



[[ 4.   0. ]
 [ 0.  -1.5]]


In [16]:

# A를 LU분해하시오
A = np.array([[1,4,1],
              [1,6,1],
              [2,-1,2]])
              
  

import scipy as sp
import scipy.linalg
A, L, U = sp.linalg.lu(A) 
print(A)
print(L)
print(U)
# 출력은 permitation된 함수, L, u 




[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.5        0.69230769 1.        ]]
[[ 2.  -1.   2. ]
 [ 0.   6.5  0. ]
 [ 0.   0.   0. ]]


linear equation solve

In [17]:
import numpy as np
a = np.array([[2,1],
              [2,1.001]])
        
b =  np.array([0,1])

sol = np.linalg.solve(a,b)
print(sol)


[-500. 1000.]


In [18]:
a@sol
# = b

array([0., 1.])

In [19]:
A = np.array([[6, -4, 1],
              [-4, 6, -4],
              [1, -4, 6]])

B = A.copy()
B[[0,2]] = B[2,0] # Row swap 
print(B)
B[:,[0,2]] = B[:,[2,0]] # Column swap
print(B)
n = len(A)              


[[ 1  1  1]
 [-4  6 -4]
 [ 1  1  1]]
[[ 1  1  1]
 [-4  6 -4]
 [ 1  1  1]]


In [29]:
A = np.array([[6, -4, 1],
              [-4, 6, -4],
              [1, -4, 6]])

B = np.array([[-14, 22],
              [36, 18],
              [6, 7]])

#row2 -> row2 - (-2/3)*row1
lam1 = A[1,0]/A[0,0]
A[1,:] = A[1,:] - lam1*A[0,:]
print(A)

# row3 -> row3 - lam2*row1
lam2 = A[2,0]/A[0,0]
A[2,:] = A[2,:] - lam2*A[0,:]
print(A)

#row3 -> lam3*row2
lam3 = A[2,1]/A[1,1]
A[2,:] = A[2,:] - lam3*A[1,:]
print(A)

# 가우스 소거법으로 하삼각행렬, 상삼각행행렬로 만들수 있다면 lU 분해법 사용 가능

#doolittle's decomposition
#A = LU
#A@x = b
#L@U@x = b, u@x = y
#L@y = b 풀수있어 L이 하삼각행렬이라 전진대입
#U@X = y 후진대입으로 풀수 있음

#LU = A.copy()
#LU[1,0] = lam1
#LU[2,0] = lam2
#LU[3,0] = lam3

[[ 6 -4  1]
 [ 0  3 -3]
 [ 1 -4  6]]
[[ 6 -4  1]
 [ 0  3 -3]
 [ 0 -3  5]]
[[ 6 -4  1]
 [ 0  3 -3]
 [ 0  0  2]]
